name: Publish Release
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  release-management:
    runs-on: ubuntu-latest
    outputs:
      new-version: ${{ steps.semantic-release.outputs.new-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            @semantic-release/exec
          dry_run: false

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.release-management.outputs.new-tag }}

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable # Set this to dtolnay/rust-toolchain@nightly

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target' # Set this to npm, yarn or pnpm.

      - name: Install dependencies
        run: npm install

      - name: Build Windows installer
        run: npm run tauri build
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY  }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          tag_name: ${{ needs.release-management.outputs.new-tag }}
          files: |
            src-tauri/target/release/bundle/msi/APP_NAME_*_x64_en-US.msi
            src-tauri/target/release/bundle/msi/APP_NAME_*_x64_en-US.msi.sig
            src-tauri/target/release/bundle/nsis/APP_NAME_*_x64_en-US.exe
            src-tauri/target/release/bundle/nsis/APP_NAME_*_x64_en-US.exe.sig
            src-tauri/target/release/latest.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}